In [2]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from pandas.plotting import scatter_matrix
from sklearn.impute import SimpleImputer
from sklearn.dummy import DummyClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings(action='ignore', category=DataConversionWarning)
warnings.filterwarnings(action='ignore', category=FutureWarning)

In [5]:
original_df = pd.read_csv("LeagueDataset.csv")
df = pd.read_csv("LeagueDataset.csv")

In [6]:
df.describe(include='all')

,c_avg_deg_cons,c_avg_dom_cons,c_avg_domdeg_cons,c_bounds_d,c_bounds_r,c_bounds_z,c_cv_deg_cons,c_cv_dom_cons,c_cv_domdeg_cons,c_domain,...,v_ratio_bounded,v_ratio_vars,v_sum_deg_vars,v_sum_dom_vars,v_sum_domdeg_vars,number_of_teams,fixtures_left,number_of_constraints,runtime,fpoints
count,110.000000,110.000000,110.000000,110.0,110.0,110.0,110.000000,110.000000,110.000000,110.0,...,110.000000,110.000000,110.000000,110.000000,110.000000,110.0,110.000000,110.000000,110.000000,0.0
mean,2.723859,5.074926,1.777857,0.0,0.0,0.0,0.578400,0.733960,0.510852,0.0,...,0.173072,0.979779,1128.718182,1156.463636,484.101291,6.0,3.818182,1.817273,9.872727,NaN
std,0.001284,0.028358,0.010039,0.0,0.0,0.0,0.005786,0.003976,0.001721,0.0,...,0.026198,0.001779,5.197268,17.673220,4.381609,0.0,2.299509,1.935212,5.462313,NaN
min,2.719130,4.983760,1.748690,0.0,0.0,0.0,0.563444,0.726093,0.506839,0.0,...,0.133005,0.978208,1113.000000,1108.000000,473.408800,6.0,1.000000,0.040000,-1.000000,NaN
25%,2.722890,5.055923,1.771370,0.0,0.0,0.0,0.574848,0.731308,0.509511,0.0,...,0.160099,0.978313,1125.000000,1147.000000,481.241800,6.0,2.000000,0.195000,6.000000,NaN
50%,2.723970,5.077870,1.779300,0.0,0.0,0.0,0.578874,0.734262,0.511242,0.0,...,0.167488,0.978417,1130.000000,1161.500000,484.575800,6.0,3.000000,0.905000,10.000000,NaN
75%,2.725060,5.095630,1.784880,0.0,0.0,0.0,0.582532,0.736607,0.512206,0.0,...,0.176471,0.980723,1131.000000,1167.750000,486.575800,6.0,6.000000,3.297500,14.000000,NaN
max,2.727490,5.132430,1.797840,0.0,0.0,0.0,0.590874,0.743839,0.514686,0.0,...,0.257353,0.985401,1136.000000,1184.000000,491.908800,6.0,8.000000,5.010000,19.000000,NaN